In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
#Leyendo archivo CSV con propiedades fisicas de galaxias
df = pd.read_csv('inferencia.csv')
df.head()

,name,objra,objdec,C,A,S,nsa_sersic_mass,LogMass,nsa_sersic_ba,nsa_sersic_n,PETRO_TH90,log_age_mean_LW,log_ZH_mean_LW,log_SFR_ssp,log_SFR_Ha,vel_sigma_Re,modelMag_r
0,manga-10001-12701,133.371091,57.598425,2.419,0.191,0.26,3.068010e+09,9.486857,0.335333,0.741845,7.880948,8.579291,-0.686187,0.279712,-0.089513,0.787103,16.38244
1,manga-10001-12702,133.685670,57.480250,2.882,0.094,0.01,5.341650e+09,9.727675,0.508217,1.442720,14.147447,8.607433,-0.534190,0.064082,-0.608526,0.788093,16.68502
2,manga-10001-12703,136.017160,57.092329,3.249,0.135,0.43,1.369350e+10,10.136514,0.205749,2.180840,13.001850,8.753122,-0.397718,0.226685,0.100403,0.503865,15.69032
3,manga-10001-12704,133.989967,57.677968,3.380,0.212,0.85,4.286640e+09,9.632117,0.150000,0.869326,28.682878,8.749540,-0.556040,-0.341232,-0.465114,0.519440,14.68778
4,manga-10001-12705,136.751375,57.451437,2.883,0.152,0.15,1.298730e+10,10.113519,0.471451,1.250460,11.039550,8.571370,-0.675505,0.467783,0.482523,0.769578,15.71422

In [10]:
#Datos faltantes por variable
df.isnull().sum()

#Porcentaje de datos faltantes por columna
#porcentaje_null = df.isnull().sum() * 100 / len(df)
#print('\n\n Porcentaje de valores faltantes por columna \n',porcentaje_null)

 Porcentaje de valores faltantes por columna
 name               0.000000
objra              0.000000
objdec             0.000000
C                  0.000000
A                  0.000000
S                  0.000000
nsa_sersic_mass    0.009876
LogMass            0.276516
nsa_sersic_ba      0.009876
nsa_sersic_n       0.009876
PETRO_TH90         0.325894
log_age_mean_LW    0.454276
log_ZH_mean_LW     0.454276
log_SFR_ssp        0.622161
log_SFR_Ha         1.599842
vel_sigma_Re       0.513530
modelMag_r         0.088880
dtype: float64

In [11]:
#Estadísticas resumidas del conjunto de datos
df.describe()

,objra,objdec,C,A,S,nsa_sersic_mass,LogMass,nsa_sersic_ba,nsa_sersic_n,PETRO_TH90,log_age_mean_LW,log_ZH_mean_LW,log_SFR_ssp,log_SFR_Ha,vel_sigma_Re,modelMag_r
count,10126.000000,10126.000000,10126.000000,10126.000000,10126.000000,1.012500e+04,10098.000000,10125.000000,10125.000000,10093.000000,10080.000000,10080.000000,10063.000000,9964.000000,10074.000000,10117.000000
mean,183.138344,28.624910,-0.098939,-3.180111,-3.203084,4.674150e+10,10.161814,-26.063981,-23.426154,15.404521,9.062482,-0.358951,-0.312412,-0.855118,0.377033,15.570126
std,76.301840,17.968381,57.986207,57.804802,57.866248,2.660245e+11,0.718922,515.713760,515.853857,10.506654,0.420297,0.250802,0.713508,1.262819,0.200348,1.063864
min,0.008808,-9.302426,-999.000000,-999.000000,-999.000000,-9.999000e+03,5.912527,-9999.000000,-9999.000000,0.223419,7.780834,-1.738662,-3.830545,-5.375214,-1.000000,11.427130
25%,128.891916,14.652696,2.866000,0.084000,0.070000,3.840210e+09,9.589929,0.433210,1.380756,9.324070,8.719238,-0.519498,-0.819611,-1.596008,0.233838,14.823970
50%,194.107467,29.368107,3.224000,0.132000,0.160000,1.547420e+10,10.193351,0.628128,2.815090,12.993234,9.046867,-0.321569,-0.278466,-0.561783,0.374381,15.609660
75%,239.689169,43.866542,3.655000,0.218000,0.310000,5.561300e+10,10.748113,0.781459,5.456550,18.509815,9.425824,-0.164714,0.222053,0.076267,0.508717,16.227040
max,359.858576,65.289735,5.599000,1.971000,8.630000,2.456760e+13,13.390363,1.000000,6.000000,148.008440,9.876999,0.148277,2.304117,3.899618,1.084997,24.802030